### ISSUE TITLE
Turn off request logging?

### ISSUE THREAD

**Issue by kengruven** [Parallels/rq-dashboard#100]
When you run rq-dashboard, it prints every GET request to stderr.

This is certainly useful for debugging rq-dashboard itself, but it's not really helpful when running a stable version of rq-dashboard for some other purpose.

I wish there were a way, externally to rq-dashboard, to make it silent except when there's an error.

**Comment by TiernanKennedy** [comment]
@kengruven did you find a solution to this?

**Comment by cbautista1002** [comment]
I would also like to see some control around how verbose `rq-dashboard` is. As I workaround, I launch `rq-dashboard` with:

```
rq-dashboard > /dev/null 2>&1
```

No output will be printed since this will forward it all to `/dev/null` where it will be discarded.

**Comment by eoranged** [comment]
Fixed in scope of #192.
Thanks @njmei
