### ISSUE TITLE
SyntaxError in 0.3.5+ under Python 2.6.6

### ISSUE THREAD

**Issue by command-tab** [Parallels/rq-dashboard#103]
I'm running rq-dashboard under Python 2.6.6, and I noticed in 0.3.5, [this line](https://github.com/nvie/rq-dashboard/blob/14527acecfc0c2be0c5bcc2812189da2b5f82bd6/rq_dashboard/web.py#L105) was introduced which throws a SyntaxError. Is there any chance of a more backwards-compatible version?

Thanks so much!

**Comment by ueg1990** [comment]
Need to replace with:
return dict((k, v) for (k, v) in input_dict.items() if v is not None)

If this is good enough, i can send a PR for this :)

**Comment by eoranged** [comment]
Fixed by #115 
@commandtab thanks for reporting.
