### ISSUE TITLE
failed jobs not showing

### ISSUE THREAD

**Issue by ccurvey** [Parallels/rq-dashboard#107]
I can bring up the dashboard and it looks great.  It tells me I have 101 failed jobs.  But when i click on the failed "queue", nothing is listed.  Am I doing something wrong?

**Comment by ccurvey** [comment]
hold off on this.  sometimes the jobs appear, sometimes they don't.  Let me dig deeper and get more detail on this.

**Comment by AshwinRamesh** [comment]
Hey @ccurvey I looked into the code. It seems to be happening in Python 3 (I was using 3.5) where it can't json encode the exception correctly it seems. I did a hot fix for myself by wrapping the exception trace in str(..) which seems to fix it temporarily and show the output

**Comment by antoine-lizee** [comment]
I'm having the same problem, but I think it's more related to `python-rq` than `rq-dashboard`. The jobs that fail get pushed in the `failed` queue but are not available, as if they had been canceled.

**Comment by antoine-lizee** [comment]
I believe this will be fixed by https://github.com/nvie/rq/pull/765

**Comment by skavie** [comment]
Encountered same issue on python 2.7 rq 0.7.0.

Upgrading to 0.7.1 which packaged nvie/rq#765 seems to have resolved it.

**Comment by QasimK** [comment]
I'm experiencing this issue currently even on the latest version. It seems to be linked to particular jobs (functions). Perhaps an issue with deserialisation?

```
rq=0.7.1
rq-dashboard=0.3.4
rq-scheduler=0.7.0
python=3.5.2
```

**Comment by jpforny** [comment]
I'm experiencing this issue on the latest version. Sometimes the jobs appear, sometimes they don't.

**Comment by eoranged** [comment]
Is It still actual?
With last versions of the dashboard this should work fine.

**Comment by ccurvey** [comment]
@eoranged I have not seen this issue in a long time.

**Comment by eoranged** [comment]
Okay. Closing this one, since nobody has faced this recently.
Feel free to reopen and provide details if the issue will reappear.
