### ISSUE TITLE
rq-dashboard not displaying correctly under https

### ISSUE THREAD

**Issue by nadermx** [Parallels/rq-dashboard#108]
I'm trying to use the rq dashboard via my flask app.  But it doesn't display correctly never loads any of the information.  But if I run it through the port with no https it works fine

**Comment by mschmo** [comment]
Can you provide any more information? Are you seeing any errors in your console when running through HTTPS?

**Comment by eoranged** [comment]
@nadermx have you been able to solve your issue? Is It still relevant?

**Comment by nadermx** [comment]
This was resolved when I most recently tried it.

**Comment by Florents-Tselai** [comment]
I'm running a flask app behind an `nginx` proxy and I've registered `rq-dashboard` as a blueprint.
and once try to open the relevant page under `https://example.com/rq` I get this

![image](https://user-images.githubusercontent.com/2118708/41155629-759938a0-6b27-11e8-9d9d-c1ef0134b054.png)


It looks like `nginx` tries to redirect to SSL (as it shoud) but somehow fails for the blueprint (the rest of the `Flask` app works fine though).

Any thoughts?

**Comment by eoranged** [comment]
@Florents-Tselai  Could you please share your nginx config or preferably minimalist configuration allowing to reproduce the issue.
Also be sure to share rq, rq-dashboard and Flask versions you use.

**Comment by Florents-Tselai** [comment]
@eoranged My bad. False alarm on my side.

For the record though: I have a main `Flask` app redirecting to a [`Dash`](https://dash.plot.ly/). In such a scenario the `rq_dashboard` blueprint should be registered after the `Flask` object has been passed to the `Dash` server ( I guess `Dash` overwrites blueprints or something.
Like this.

```
server = flask.Flask(__name__)

dash_app = create_dash_app(flask_server=server, dashapp_start='reports')

import rq_dashboard
server.config.from_object(rq_dashboard.default_settings)
server.register_blueprint(rq_dashboard.blueprint, url_prefix="/rq")
```


* Apologies for the off-topic. Leaving it here in case one lands from Google.

**Comment by eoranged** [comment]
@Florents-Tselai thanks for sharing this. I hope It will be of help to somebody.
