### ISSUE TITLE
UI too slow to load or hangs when jobs with long descriptions are queued

### ISSUE THREAD

**Issue by joowani** [Parallels/rq-dashboard#110]
First of all, I really appreciate your work on rq-dashboard! I find it very useful and use it almost everyday. There is one small problem, however, which makes the dashboard hard to use in some cases.

When I have RQ jobs queued with very long descriptions (e.g. a function call with a list argument containing 1000s of elements), the UI takes a _very_ long time to load or simply hangs. I do **this** to get around the issue at the moment: https://github.com/ducu/rq-dashboard/pull/109 (limiting the number of characters to 100 by default and giving the user control over it via a new command line option). The PR is probably a little too hacky to merge but I think some sort of control over the number of characters coming from the RQ jobs is definitely needed. Please take a look.

Thanks a bunch!
Joohwan

**Comment by antoine-lizee** [comment]
I implemented something similar out-of-library to limit the size of individual arguments showed in the description. It's ugly because it involves 10 lines of copy-pasting but doesn't access/modify the library. I too think it would be awesome to have it!

```
from rq.compat import as_text
from rq.job import Job as DefaultJob


def cut_string(string, n=80):
    if len(string) > n:
        return string[0:(n-2)] + '...'
    else:
        return string


class Job(DefaultJob):
    """Monkey patches the default Job class to avoid having an extremely long description."""
    
    def get_call_string(self):
        """Returns a string representation of the call, formatted as a regular
        Python function invocation statement.
        """
        if self.func_name is None:
            return None

        arg_list = [as_text(repr(arg)) for arg in self.args]

        kwargs = ['{0}={1}'.format(k, cut_string(as_text(repr(v)))) for k, v in self.kwargs.items()]
        # Sort here because python 3.3 & 3.4 makes different call_string
        arg_list += sorted(kwargs)
        args = ', '.join(arg_list)

        return '{0}({1})'.format(self.func_name, args)


queue = Queue(..., job_class=Job)
```
