### ISSUE TITLE
jobs always say "Failed 4 hours ago" with None listed as caught Error

### ISSUE THREAD

**Issue by podopie** [Parallels/rq-dashboard#117]
In my default queue this information always shows up, even if the job is only 1-5 seconds old. My guess is that it shouldn't be if the job hasn't run yet and is in the default queue.

Data shows up correctly in the regular queue.

Not sure if it matters but setup is python 2.7, flask, rq-scheduler, and this.

**Comment by emin63** [comment]
Just started using python-rq and rq dashboard. Having same issue with python 3.4.

Hopefully an easy fix since so far python-rq and the dashboard look great.

Thanks.

**Comment by eoranged** [comment]
Haven't seen the issue for a while.
Closing this. Feel free to reopen if you still face It with recent versions of RQ and RQ Dahsboard.
