### ISSUE TITLE
0.3.8 not on pypy

### ISSUE THREAD

**Issue by mikob** [Parallels/rq-dashboard#120]

**Comment by eoranged** [comment]
Thanks for noticing this, @mikob!
I'm currently not a maintainer of PyPI index for rq-dashboard.
Sent email to @nvie recently with request of adding me as maintainer, but no response yet.

**Comment by eoranged** [comment]
Now It's on PyPI. Thanks @ducu!

**Comment by nvie** [comment]
Whoops, missed this one in a pile of emails. Good to see it's sorted out!
