### ISSUE TITLE
RQ-Dashboard on Heroku not loading REDIS_URL

### ISSUE THREAD

**Issue by skavie** [Parallels/rq-dashboard#121]
I have installed RQ-Dashboard onto my Flask application, and have a page that prints out the `REDIS_URL` variable from my environment configuration.

Testing application locally with both `localhost:6379` and my actual Heroku Redis url `redis://h:password@host:port` works; the HTML prints out `REDIS_URL` settings correctly, the dashboard shows the worker statuses correctly, and I am able to queue workers, etc. etc.

Moving the application onto Heroku results in a HTTP500 Internal Server error when accessing the dashboard url.

Looking at the application logs results in:
`ConnectionError: Error 111 connecting to localhost:6379. Connection refused.`

If it was a problem with the `REDIS_URL` setting on Heroku I would have expected the HTML print out to be NONE and also not able to queue any jobs. But the print out gives the expected value and I can still queue and process jobs. 

I am on 0.3.7 of rq-dashboard and 0.7.1 of rq. Thoughts appreciated, thanks.

**Comment by eoranged** [comment]
Hello, @skavie!

Could you please provide the code you used to expose REDIS_URL to RQ Dashboard on Heroku?

RQ Dashboard is not designed to run out-of-box on Heroku and needs additional configuration to get REDIS_URL and maybe some other parameters from environment variables (or whichever way they provide settings to applications).

**Comment by skavie** [comment]
Hello, and thanks for the quick response @eoranged !

This is what I have in my app.py.

```
import os
import rq_dashboard

from flask import Flask, request, render_template, redirect, url_for, flash
from flask_restful import Resource, Api, abort, reqparse
from flask_sqlalchemy import SQLAlchemy
from rq import Queue
from rq.job import Job
from worker import conn

# basic app config
app = Flask(__name__)
app.config.from_object(os.environ['APP_SETTINGS'])
app.config.from_object(rq_dashboard.default_settings)
#app.config.from_object(os.environ['REDIS_URL'])     # uncommenting this line results in error

# start other classes
api = Api(app)
db = SQLAlchemy(app)
qh = Queue('high', connection=conn)

env = os.environ['APP_SETTINGS']
rd = os.environ['REDIS_URL'] # printing this gives me the expected REDIS_URL

app.register_blueprint(rq_dashboard.blueprint, url_prefix="/queue/dashboard")
```

REDIS_URL is set up as an environment configuration value and is in the redis url format:

`redis://h:xxxx@xxxx.eu-west-1.compute.amazonaws.com:8889`

From the readme on this repo there was a reference to configuration settings `RQ_DASHBOARD_*`. I tried doing setting up a whole series of config values on Heroku, but with no positive result (`RQ_DASHBOARD_REDIS_HOST`, `RQ_DASHBOARD_REDIS_PORT`, `REDIS_HOST`, `REDIS_PORT` and `REDIS_PASSWORD`).

Thanks in advance.

**Comment by skavie** [comment]
Apologies I can see what's wrong now. I had overwritten my environment variable with the one from the RQ-Dashboard default settings. Swapping the sequence around made it work. Thanks for the help!
