### ISSUE TITLE
pip install fails: No matching distribution found for rq-dashboard==0.3.8

### ISSUE THREAD

**Issue by jfunez** [Parallels/rq-dashboard#126]
### Issue:

pip install fails because couldn't find the package:
`No matching distribution found for rq-dashboard==0.3.8`

### how to reproduce the error:
1.  `mkvirtualenv test_rq`
2. by default it will use python 2.7.x
3. `pip install rq-dashboard==0.3.8`
4. Error raised: 
```
$ pip install rq-dashboard==0.3.8
Collecting rq-dashboard==0.3.8
  Could not find a version that satisfies the requirement rq-dashboard==0.3.8 (from versions: 0.1.0, 0.2, 0.3, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7)
No matching distribution found for rq-dashboard==0.3.8
```

**Comment by eoranged** [comment]
Hello, Juan!
Thanks for the report. This does not work for me either for some strange reason.
I'll look into It this weekend.

**Comment by eoranged** [comment]
Sorry for delay.
Looks like the distribution was not uploaded properly at the time of releasing 0.3.8 on PyPI.
Now installing should work just fine.

**Comment by jfunez** [comment]
Superb! Thanks!
