### ISSUE TITLE
Support multiple RQ instances

### ISSUE THREAD

**Issue by GerardSoleCa** [Parallels/rq-dashboard#128]
Hello,

I'll open a PullRequest which adds support for multiple RQ instances.

When using the Flask Blueprint, it is possible to pass an array of Redis URL to the rq-dashboard plugin.

```python
app.config.update(REDIS_URL=['redis://localhost:6379/0', 'redis://localhost:6379/1'])
app.register_blueprint(rq_dashboard.blueprint, url_prefix='/rq')
```

When passing an array of connections, it will appear on the dashboard a new block with a dropdown, which lets changing the RQ instance to be observed.

![screen shot 2017-08-21 at 18 59 33](https://user-images.githubusercontent.com/2593956/29530199-eacc7868-86a2-11e7-8023-ce7ef1f39a27.png)

By default, rq-dashboard will show the information of the first RQ, but selecting another one, will trigger a swap on the backend, so it will start showing the new rq-instance data.

**Comment by GerardSoleCa** [comment]
Hi @eoranged and @nvie, have you had some time to review this Issue and PullRequest?

It would be awesome to see different Redis queues, so for us, it is a really nice feature that would help on our day to day work.

I'll stay tuned on this thread, so if you have any questions, just drop them :)

Thanks!

**Comment by eoranged** [comment]
Hi, Gerard!
I have briefly reviewed the code some time ago and had some thoughts about the idea. After some time I see that idea is good and It might be useful for others.
Thanks. Merged.

**Comment by GerardSoleCa** [comment]
Your welcome!
Could you please bump the package, so it can be installed through pip.
Thanks!
