### ISSUE TITLE
Mabye move rq-dashboard to the rq organisation

### ISSUE THREAD

**Issue by samuelcolvin** [Parallels/rq-dashboard#143]
rq has now moved to an organisation https://github.com/rq.

Would you consider moving `rq-dashboard` into that organisation? Obviously all collaborators can become collaborators on the organisation.

**Comment by eoranged** [comment]
Hello, Samuel!
I'm curious what is the main point on moving the project to rq organization?
We currently use the project internally at Parallels and we thinking about moving project to company's public github account, so we can develop It during work hours. But It is still being discussed.
I'll be glad to hear out your point of view, so we have more information before making either decision.

**Comment by samuelcolvin** [comment]
A few reasons:
1. So it's easy for new users of rq to find useful associated tools.
2. To encourage input on all the rq related repos from people contributing from any of the repos. For example at TutorCruncher we use rq but currently not rq-dashboard but as a member of the rq organisation I might well chip in and contribute to rq-dashboard.
3. "Group ownership" of associated projects reduces the chance that a project gets abandoned - if a project is part of the organisation and it's main maintainer ceases to work on it, it's easy for other members of the organisation to take over maintenance if the project is useful.

None of these reasons are unique to rq, lots of other projects and groups of projects I think have benefited a lot from being part of an organisation. In particular aio and pallets come to mind (although I agree they're much bigger)

Of course it's entirely up to you and rq-dashboard is still much appreciated here or in your companies organisation.

**Comment by eoranged** [comment]
These reasons look good to me. I would like to hear out the community, though.
I took over project maintenance because at some point I found that It's not building on python 2.x and my current goal is to ensure project survival and ability to run in environments where users do use It. And If there are people who really want to spare some time and energy for the project (many of us don't have many of these resources to spare) I would happily move It to rq organization.

**Comment by eoranged** [comment]
I have thought about It once again and now I'm sure It will be the best option.
@nvie, @ducu, @tcorbettclark, @joostdevries do you want to join rq organization as collaborators?

**Comment by ducu** [comment]
Hey sure, thank you, but I can't promise I'll be active for now

**Comment by eoranged** [comment]
This discussion seems to be dead, so closing this.
Feel free to reopen If you are still interested.
