### ISSUE TITLE
Drop Python 2.6 support

### ISSUE THREAD

**Issue by eoranged** [Parallels/rq-dashboard#145]
From [PEP 361](https://www.python.org/dev/peps/pep-0361/#release-lifespan):
Python 2.6.9 is the final security-only source-only maintenance release of the Python 2.6 series. With its release on October 29, 2013, all official support for Python 2.6 has ended. Python 2.6 is no longer being maintained for any purpose.

**Comment by hugovk** [comment]
Here's the pip installs for rq-dashboard from PyPI for last month:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 3.6            |   52.4% |          6,751 |
| 2.7            |   40.7% |          5,237 |
| 3.5            |    5.9% |            758 |
| 3.4            |    1.0% |            130 |
| 2.6            |    0.0% |              1 |

Source: `pypinfo --start-date -31 --end-date -1 --percent --pip --markdown rq-dashboard pyversion`

**Comment by rooterkyberian** [comment]
This is inline with `rq`, which already removed 2.6 support some time ago https://github.com/rq/rq/pull/874 .

**Comment by hugovk** [comment]
Thanks, that's good to know. Even more reason to bury 2.6 and move on!

**Comment by eoranged** [comment]
Thanks, @rooterkyberian. then we'll need to use rq<=0.8.2 for python 2.6 for now.
