### ISSUE TITLE
Add tooltips for the Compact/Empty buttons

### ISSUE THREAD

**Issue by nvie** [Parallels/rq-dashboard#15]

**Comment by onilton** [comment]
What (text) would be inside the tooltips? Can you provide examples of the text content and tooltip style?

**Comment by nvie** [comment]
Just an HTML title attr, I'd say, nothing special. The compact button should read "remove all stale jobs from this queue (non-destructive)". The empty button should read "remove all jobs from this queue (destructive)".

**Comment by onilton** [comment]
We could use twitter's bootstrap tooltip or popover:

http://twitter.github.io/bootstrap/javascript.html#tooltips

http://twitter.github.io/bootstrap/javascript.html#popovers

which one do you prefer?

**Comment by nvie** [comment]
A tooltip is more appropriate in this case, I think.

**Comment by onilton** [comment]
I submitted a pull request that adds those tooltips. I highlighted the "destructive" word in the text.

**Comment by onilton** [comment]
Anything more that you think is needed in this commit/pull request?

**Comment by nvie** [comment]
Nope. thanks!
