### ISSUE TITLE
Broken images in the README

### ISSUE THREAD

**Issue by mgedmin** [Parallels/rq-dashboard#152]
Screenshot of the GitHub repository page:
![ekrano nuotrauka is 2018-04-12 18-47-10](https://user-images.githubusercontent.com/159967/38688514-f2a130c8-3e81-11e8-84cf-c5f8b6670820.png)

**Comment by eoranged** [comment]
I was planning to fix this for a long time alongside with changes in README.
Luckily, I've completely forgot what I was planning to write there, so now screenshots are in place.
