### ISSUE TITLE
Release 0.3.12

### ISSUE THREAD

**Issue by kitsuyui** [Parallels/rq-dashboard#159]
Hi @eoranged

We are using forked version of rq-dashboard in our project because of the `tests` confliction.
Would you please release a new version including #158 ?

**Comment by eoranged** [comment]
Hi!
No problem. I was planning to do It anyways. 
Here you go: https://pypi.org/project/rq-dashboard/0.3.12/
And just in case you can specify project in requirements.txt as `-e git://github.com/eoranged/rq-dashboard.git@3bbd898b210e3c3501a53fe4420c499bcd9b34a7` (you can omit commit part to stick with master branch) and It will be pinned to specific commit/branch rather then to latest release from PyPI If there is something you need to use right away.

**Comment by kitsuyui** [comment]
@eoranged 
Thank you!

We had already used that .git repo pinning style.
But -e git+... insallation seems contains tests package yet.
So we had made other branch that isn't contain tests directory and had used that as workaround.
https://github.com/kitsuyui/rq-dashboard/tree/tmp-remove-tests

This is not important any more.
We are already happy that using new version.
