### ISSUE TITLE
Username/password safety issue

### ISSUE THREAD

**Issue by jeffery9876** [Parallels/rq-dashboard#175]
Hi,

Currently the username/password are provided explicitly from the command line, which makes the credentials visible to other users on the system. They can see by checking ‘ps -ef | grep rq-dashboard’

There are two ways to improve the security hazards:

1. Using a config file with username/password
2. Reading the pre-defined system variables directly from two-dashboard. 

Either options is easy to implement but greatly improved the security. If possible, I hope this can be done before version 1.0 is released

**Comment by selwin** [comment]
RQ already supports a config file. You could put your Redis URL inside your config file and run your worker as such: `rq worker -c my_settings`. This is documented on this page: https://python-rq.org/docs/workers/

Reading Redis URL through environment variables is not yet supported but I'd accept a PR for that :)

**Comment by eoranged** [comment]
This is repository for RQ Dashboard, not RQ itself.
If you have an issue with RQ, please report issue to https://github.com/rq/rq/
As for RQ dashboard, It supports configuration via environment variables (see docs or source code). All environment variables are to be named like cli options, but with `RQ_DASHBOARD_` prefix, with hyphens replaced with underscores and capitalized. So `--redis-url` can be specified as environment variable like this: `RQ_DASHBOARD_REDIS_URL=redis://password@127.0.0.1:6379/0`

Closing the issue.
Feel free to reopen if you have any additional questions.

**Comment by jlbgit** [comment]
In case anyone comes across this again - @eoranged I think there is a **:** missing in the above post, for me this worked:

`RQ_DASHBOARD_REDIS_URL=redis://:password@127.0.0.1:6379/0`

Thanks in any case!

**Comment by Emekaborisama** [comment]
> In case anyone comes across this again - [@eoranged](https://github.com/eoranged) I think there is a **:** missing in the above post, for me this worked:
> 
> `RQ_DASHBOARD_REDIS_URL=redis://:password@127.0.0.1:6379/0`
> 
> Thanks in any case!

Thank you so much. you are a super hero
