### ISSUE TITLE
Redis ssl cert handling

### ISSUE THREAD

**Issue by lbenarous-plaid** [Parallels/rq-dashboard#177]
Hi,

I've really enjoyed using rq-dashboard but I'm having issues using it with redis connections that require specific ssl configuration (related to the `ssl=False, ssl_keyfile=None, ssl_certfile=None, ssl_cert_reqs=u'required', ssl_ca_certs=None` parameters in https://redis-py.readthedocs.io/en/latest/#redis.Redis ).

For my particular case, I would like to be able to set `ssl_cert_reqs=None` as a parameter to the Redis object created in https://github.com/eoranged/rq-dashboard/blob/master/rq_dashboard/web.py#L41.

Is there already a way for me to do this, or would it possible to add this as a command line parameter or some kind of config file parameter?

Thanks for the help

**Comment by lbenarous-plaid** [comment]
I'd also be happy to open a PR if that can help.

**Comment by eoranged** [comment]
I'm thinking about redesigning configuration format a bit, will keep this in mind while doing so.
Also, I'm planning to replace Redis instance with StrictRedis.
For now this can be worked around by using [redis-py 2.10.6](https://github.com/andymccurdy/redis-py/releases/tag/2.10.6).

**Comment by lbenarous-plaid** [comment]
this is resolved with `redis >= 3.2.1` and using the full redis url: `rq-dashboard --port 8080 --redis-url rediss://<redis host>:6379`

**Comment by DennyWeinberg** [comment]
How to prevent  `Error 1 connecting to abc.eu-west-1.compute.amazonaws.com:14280. [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129).`?
