### ISSUE TITLE
get_failed_queue() function has been removed. Please use FailedJobRegistry(queue=queue) instead.

### ISSUE THREAD

**Issue by neuronflow** [Parallels/rq-dashboard#178]
python rq removed this functionality so rq-dashboard crashes
get_failed_queue() function has been removed. Please use FailedJobRegistry(queue=queue) instead.

**Comment by eoranged** [comment]
@meowlz rq-dashboard is currently marked as incompatible with rq>=1.0.0. I'm planing on fixing this, but during recent months I had little spare time to do so.
Feel free to submit pull request for It.

Migration to 1.0 is tracked in #172 , please use It for tracking and further discussion.
Closing this as duplicate.
