### ISSUE TITLE
Support multiple Redis connections at the same time

### ISSUE THREAD

**Issue by nvie** [Parallels/rq-dashboard#18]
This is kind of a thought experiment, really. I'm not sure whether this would really be useful, even. But if there is a good use case for this, it should be interesting to add this. The UI could present a drop down list to select which Redis connection to show the RQ details for.

**Comment by bradq** [comment]
Just to note, this functionality would be really handy for us, and is a blocker to using it (tons of different Redis servers/DBs, and too many resources needed to be running dozens of Flask apps to justify it). Sorry that I don't have time to send in a PR at the moment, just figured I'd note that I'd consider it quite handy. This project has been quite handy on development servers though...thanks much for your work!
