### ISSUE TITLE
Drop support for Python 3.4 and 2.7

### ISSUE THREAD

**Issue by eoranged** [Parallels/rq-dashboard#180]
We don't actually need to support all Python versions RQ does, so It's worth dropping support for old 3.x versions and probably 2.7 after LTS release.

**Comment by homeworkprod** [comment]
Which version is planned to be an LTS version?

**Comment by eoranged** [comment]
Not sure. But I'd like to drop Python 3.4 support sometime soon.
Support for 2.7 is good to have and will be there for a while, since there are many people who still use It.

**Comment by coolhacker170597** [comment]
Support for 2.7 will drop too.

**Comment by eoranged** [comment]
0.x branch will be the last supporting Python 2.7.
While It will be possible to run application using RQ 1.0+ with Python 2.7, the dashboard should be deployed with Python 3.5.3+. It is backward-compatible approach, since dashboard running with Python 3.x will be able to unpickle jobs serialized with 2.7.
