### ISSUE TITLE
Hide worker list by default

### ISSUE THREAD

**Issue by ibrahim12** [Parallels/rq-dashboard#186]
- Currently workers list can be hidden by toggle button. When we have workers more then 50 it creates a long right container and pushes the job list way down.

What about hiding worker list by default and clicking `toggle` button will show it ? 

<img width="924" alt="Screen Shot 2019-07-04 at 3 31 12 PM" src="https://user-images.githubusercontent.com/1056163/60656169-d21aac80-9e70-11e9-83d2-77bc9ee2bce6.png">

**Comment by eoranged** [comment]
Good Idea, but we need to set up some threshold for this (E.g. If there are couple of workers, no need to hide workers list by default).
But in general It is a good thing to do. My installation contains dozens of workers and It will be useful.
