### ISSUE TITLE
What about having a running job view per queue

### ISSUE THREAD

**Issue by ibrahim12** [Parallels/rq-dashboard#187]
Proposal to have a view that shows currently running jobs. 

- Job can be canceled or deleted
- Can stop all jobs via button click

**Comment by eoranged** [comment]
It will require to refactor some internals, so we will work with registries instead of plain queues.
And also we will need to drop support for RQ prior to 1.0, which I want to keep for a couple of months.

**Comment by harlowja** [comment]
This sounds pretty nice. We'd very much use it :)

**Comment by eoranged** [comment]
RQ does not have support for canceling running job, so It is impossible to do in dashboard.
Remaining is done in master (started registry view) and will be accessible in 1.0.
