### ISSUE TITLE
Order in failed jobs is wrong

### ISSUE THREAD

**Issue by ibrahim12** [Parallels/rq-dashboard#191]
-Currently failed jobs order is incorrect. It is sorted by queue.

Say we have three queue, high, low, default.

Failed jobs shows on the UI are currently in below order 

- all sorted `high` jobs
- all sorted `low` jobs
- all sorted `default` jobs

But it should be sorted globally.
sorted([jobs in low, high, default])

**Comment by eoranged** [comment]
Fixed in master

**Comment by eoranged** [comment]
Fixed in release 0.5.3.
