### ISSUE TITLE
New release to pick up recent fix

### ISSUE THREAD

**Issue by gauravmk** [Parallels/rq-dashboard#195]
I'm hitting an issue that's solved by https://github.com/eoranged/rq-dashboard/commit/b603f118b77818afb8db64922ff680ffa39c0db7. Was wondering if we could get a minor release that includes that fix. I can't downgrade to before the issue was introduced since it was part of the 0.5.0 release which also added support for rq 1.0

**Comment by eoranged** [comment]
Hello, @gauravmk!
I need just a little time to clean things up and test this more thoroughly.
You can expect release in coming days.

**Comment by eoranged** [comment]
Version 0.5.3 with all related fixes is released. On my local setup there seems to be no new issues.
If there are any new problems, feel free to create new issue here.
I'm closing this issue now, feel free to reopen If you feel that there is something else should be done in scope of It.
