### ISSUE TITLE
Uncaught TypeError: Cannot use 'in' operator to search for 'length' in redis://1.2.3.4:6379

### ISSUE THREAD

**Issue by kpurdon** [Parallels/rq-dashboard#212]
A single instance is returned as a string, but the js is expecting a single element list.

```
Uncaught TypeError: Cannot use 'in' operator to search for 'length' in redis://1.2.3.4:6379
    at C (jquery.min.js:2)
    at Function.each (jquery.min.js:2)
    at failed:335
    at Object.success (failed:267)
    at u (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at k (jquery.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2)
```

**Comment by karls** [comment]
I also just ran into this. It's rather strange — this happens if I have `REDIS_URL` in my application config. However, if I change it to, say, `REDISS_URL`, it will work. It looks like rq-dashboard is doing something funky with certain keys in the application config.

**Comment by eoranged** [comment]
What RQ dashboard version do you use?

**Comment by karls** [comment]
0.5.3, although I made my comment after trying master directly. I'm AFK for a couple of hours. Will try later.

**Comment by kpurdon** [comment]
@eoranged sorry for not including version, I'm using 0.5.3.

**Comment by karls** [comment]
I did some more testing with this, on version 0.5.3.

It seems like there are two problems. The first problem is the error that's mentioned in the title of if this issue, which seems to occur if I put `REDIS_URL` in the application config. If I change it to, say, `REDISS_URL` this error will not be thrown. It also looks like this does not actually stop the dashboard from working correctly.

The second issue, which does prevent the dashboard from working correctly, is a CSP issue. I'm using CSP via the [Flask-Talisman](https://github.com/GoogleCloudPlatform/flask-talisman) library. It looks like there is some template rendering or something happening that is using `eval` in Javascript? Essentially, if I don't have `'\'unsafe-eval\''` in my CSP, an error gets thrown from underscore.js:
```
underscore-min.js:29 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive:
```

If I add `'\'unsafe-eval\''`, the dashboard loads correctly and everything seems to work.
