### ISSUE TITLE
paginate dashboard items

### ISSUE THREAD

**Issue by bttnns** [Parallels/rq-dashboard#23]
Currently, say if I have many jobs (10's of thousands) in a certain queue the dashboard attempts to load every job that is inside of that queue.  This causes rq-dash to crash because it attempts to load too many jobs at once.  I believe it would have a better UX if the job list was paginated.

The worker list would also be nice to have a count of number of workers and paginated as well.

**Comment by nvie** [comment]
+1 on this one. If somebody wants to contribute a patch, I'll be happy to facilitate and pull.

**Comment by mgax** [comment]
I'd really find pagination useful too, my use case is enqueueing thousands of tiny jobs and keeping an eye out for errors. Here's a quick stab at limiting the output (depends on [rq#178](https://github.com/nvie/rq/pull/178)): https://github.com/mgax/rq-dashboard/commit/8f4916ee14. It would probably need next/previous links and other polish.

**Comment by Alex-Poon** [comment]
+1 my dash crashes

**Comment by nvie** [comment]
I will pull this in when the next/previous links have been added as well. The new queue API that can be used is:

```
q.get_jobs(0, 20)
```

and will be released as part of rq==0.3.8.

**Comment by sylvinus** [comment]
+1, I also have 1000s of jobs and this makes the dashboard unusable. I'd be happy to test a patch

**Comment by onilton** [comment]
@nvie I opened a pull request that adds pagination.

Please, take a look and tell me if anything needs to be improved. I am not a great programmer in javascript, underscorejs and flask/python, but I tried and managed to develop something that I think it's working. I would be glad to receive some tips on the code.

If anyone wants to try the code just clone my fork at https://github.com/oniltonmaciel/rq-dashboard .

Note that you will need the last version of rq from git (as the pip and other versions won't work) :

https://github.com/nvie/rq
