### ISSUE TITLE
Prevent leaked secrets

### ISSUE THREAD

**Issue by goldstar611** [Parallels/rq-dashboard#232]
If you pass secrets to the worker via arguments then those are displayed on the dashboard.

Is there a way to prevent certain (or any) arguments from being displayed?
Kind of like how django and other packages will sanitize *key* *pass* *secret* etc.

**Comment by eoranged** [comment]
Hello, @goldstar611 !
Could you be a little bit more specific? Which secrets and how do you pass them?
An example (with dummy secrets) will be wonderful.

Also, could you please tell us which RQ Dashboard version do you use? We have applied some fixes for similar problems recently.

**Comment by goldstar611** [comment]
We have a GitHub repo deploy key that is passed to each worker so that it only has access to the repo it needs. It is passed as part of a dictionary with other info such as the repo location.

For versions, I'm using rq-dashboard 0.5.3 on python 3.7

**Comment by eoranged** [comment]
Oh, I've got the problem.
We can use the same approach as Sentry does with some output sanitising by default and ability to override. I'll think It through since It is definitely a must-have feature.

**Comment by goldstar611** [comment]
That's great news!

I was able to find what Django does at https://github.com/django/django/blob/a8e2a9bac6e548d6ab2e13af6171d2fdd3b8055b/django/contrib/auth/__init__.py#L47

```Python
    SENSITIVE_CREDENTIALS = re.compile('api|token|key|secret|password|signature', re.I)
    CLEANSED_SUBSTITUTE = '********************'
    for key in credentials:
        if SENSITIVE_CREDENTIALS.search(key):
            credentials[key] = CLEANSED_SUBSTITUTE
```

**Comment by eoranged** [comment]
This is also affected by #309

**Comment by goldstar611** [comment]
Upon reviewing the rq source code, displaying secrets can be avoided if you manually enqueue a `description`, then HTML template will use `description` argument and not `data` argument.

so change 
```python
rq_queue.enqueue('rq_clone_task.start_clone', job_data_with_secrets)
```
to
```python
rq_queue.enqueue(f='rq_clone_task.start_clone',
                 description="Job Description",
                 data=job_data_with_secrets)
```
