### ISSUE TITLE
Public channel to interact with users/developers?

### ISSUE THREAD

**Issue by harlowja** [Parallels/rq-dashboard#255]
Is there any slack or discord channel where things are discussed?

**Comment by eoranged** [comment]
Nobody asked this before, so here we go: https://discord.gg/Sj2P5KH
I'll add the link to README a bit later. And It will be a bit lonely there for some time.
I will also ask Selwin to join us there :)

**Comment by harlowja** [comment]
Awesome, I'll jump on next week.

**Comment by eoranged** [comment]
I gave It some thought and see no reason for the channel.
Things can be discussed even more effectively here on github.

**Comment by rpkak** [comment]
I created a chat for rq that can be found [here](https://python-rq.org/chat/). Join if you want.
