### ISSUE TITLE
Ability to disable empty button

### ISSUE THREAD

**Issue by harlowja** [Parallels/rq-dashboard#256]
We are currently using rq and rq-dashboard for an internal job/data system (where jobs are programmatically submitted); one of the features that we would like the ability to control is to be able to disable the 'empty' button (because of how such a feature doesn't really make much sense when an automated system is submitting and waiting on jobs). Is it possible to make it so that we can (via configuration) turn it on/off (default to on I guess?)

**Comment by lance0805** [comment]
I also have the same needs, currently the empty button is not displayed in the failed, but sometimes a lot of jobs are not idempotent. if there are too many failures, there is no place to clean them together.

**Comment by eoranged** [comment]
This can be implemented in scope of #309

**Comment by gnomeby** [comment]
This was done in this commit: https://github.com/Parallels/rq-dashboard/commit/026aef1d30ed712e16da3d814b2651fa0a7d416a
