### ISSUE TITLE
strangeness when using blueprint

### ISSUE THREAD

**Issue by sburns** [Parallels/rq-dashboard#27]
I took a screencast of this issue, you can see it [here](https://vimeo.com/59070192). 

From the same machine, `rqinfo` runs fine while the `RQDashboard` blueprint hooked into an existing flask app is very flaky.

Notably, when running the dashboard as a standalone app (`$ rq-dashboard -u …`) the dashboard shows none of this wonkiness.

**Comment by nvie** [comment]
I think what you're seeing here is the dashboard page doing a full refresh, after which the list is empty and new jobs are dynamically loaded with internal AJAX calls. By the time those are finished loading (could it be that these are large jobs or large exception tracebacks?), the page refreshes again, probably.

Why the blueprint performs worse than the standalone app, I can't tell.

A solution could be to add a `--interval` flag and set that a bit lower (see also #26).

**Comment by sburns** [comment]
Specifying a longer interval doesn't address this. Same behavior, just on a longer timescale.

**Comment by nvie** [comment]
:(

**Comment by sburns** [comment]
Got it!

I was finally was able to generate some sort of stack trace (hint: by refreshing quickly)…

```
<snip>
  File "/home/burnsss1/Code/ebrlweb/ebrlweb/views.py", line 24, in decorator
    return f(*args, **kwargs)
  File "/home/burnsss1/envs/wsgi/lib/python2.7/site-packages/rq_dashboard/dashboard.py", line 76, in overview
    failed = Queue('failed')
  File "/home/burnsss1/envs/wsgi/lib/python2.7/site-packages/rq/queue.py", line 46, in __init__
    self.connection = resolve_connection(connection)
  File "/home/burnsss1/envs/wsgi/lib/python2.7/site-packages/rq/connections.py", line 64, in resolve_connection
    'Could not resolve a Redis connection.')
NoRedisConnectionException: Could not resolve a Redis connection.
```

Ok, so at some point `push_connection` is breaking down right? The only difference between the standalone app and the blueprint is the web server (Apache/2.2.15 (Unix) DAV/2 mod_wsgi/3.4 Python/2.7.3) which got me thinking about how I'm managing the WSGI layer with `<VirtualHost>`. Originally I had three threads setup for the WSGIDaemonProcess, but `<hand waving>` lowering it to 1 stopped multiple threads from hitting the `LocalStack` quickly which stopped what looked to be the dropped Redis connections in the UI `</hand waving>`.

**Comment by nvie** [comment]
Glad you found it!
