### ISSUE TITLE
How to use multiple Redis connections without changing source code? 

### ISSUE THREAD

**Issue by nikkonrom** [Parallels/rq-dashboard#270]
I want to monitor multiple RQ instances on 5 Redis clusters. So i have 5 Redis servers and want to switching between them to observe.
I found this: https://github.com/Parallels/rq-dashboard/issues/128
If I fully understand author, for multiple RQ instances usage, I have to fork repository and register my own blueprint with multiple urls that overrides args passed to dashboard.
But is there way to pass multiple Redis connection urls as arguments or something else **without forking repo**?

**Comment by eoranged** [comment]
Yes, just provide REDIS_URL parameter in config as a list like this:
`REDIS_URL = ['redis://redis1.example.com', 'redis://redis2.example.com:6380?db=3']`
There is no need to fork a repo to do this. It works with package installed from pip.

**Comment by nikkonrom** [comment]
@eoranged Thanks, it's worked

**Comment by Leke-Ariyo** [comment]
Hi, @eoranged 
docker run -p 9181:9181 -e RQ_DASHBOARD_REDIS_URL = ['redis-url-1:port', 'redis-url-2:port'] eoranged/rq-dashboard

I tried it this way but keep getting:
  File "/usr/local/lib/python3.8/site-packages/redis_sentinel_url.py", line 162, in connect
    raise ValueError('Unsupported redis URL scheme: {}'.format(parsed_url.scheme))
ValueError: Unsupported redis URL scheme:
  File "/usr/local/lib/python3.8/site-packages/redis_sentinel_url.py", line 162, in connect
    raise ValueError('Unsupported redis URL scheme: {}'.format(parsed_url.scheme))
ValueError: Unsupported redis URL scheme:
