### ISSUE TITLE
how can i access a protected redis server?

### ISSUE THREAD

**Issue by williamfzc** [Parallels/rq-dashboard#302]
hi :)

my redis server started with `["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PWD}"]`. so it required a password.

and i do not know how to pass my password to dashboard. 

```
- RQ_DASHBOARD_REDIS_URL=redis://<redis:6379>
- RQ_DASHBOARD_USERNAME=rq
- RQ_DASHBOARD_PASSWORD=password
```

username and password here will be only used for dashboard itself right? 

I did not find a correct way in README. and what should i do?

**Comment by coolhacker** [comment]
Hey @williamfzc
Try using RQ_DASHBOARD_REDIS_PASSWORD option. In the master branch this option marked as deprecated and in the near future the documentation will be updated for a new redis setting

**Comment by eoranged** [comment]
You can just put the password in Redis URL like this: `redis://:<password>@127.0.0.1:6379` (remember to change 127.0.0.1 and 6379 to actual host and port where your redis server is running)

**Comment by williamfzc** [comment]
thanks guys, it works :)

I think it should be noticed in doc
