### ISSUE TITLE
Home link does not use the url_prefix

### ISSUE THREAD

**Issue by paulocheque** [Parallels/rq-dashboard#31]
It should be a link to "/rq" or "/#{url_prefix}", but it appears to be a simple "/"

**Comment by nvie** [comment]
Yes, you're correct.

**Comment by sylvinus** [comment]
Fixed this one and most importantly the URLs of the AJAX calls here:
https://github.com/pricingassistant/rq-dashboard/commit/b967525025316bb25d2d1fb62b20cca988531e02
