### ISSUE TITLE
Unable to empty failed queue

### ISSUE THREAD

**Issue by toshitanian** [Parallels/rq-dashboard#331]
There is no 'Empty' button on dashboard of failed queue. It's been very useful when testing.
It existed until 0.5.3. I want it back.

![image](https://user-images.githubusercontent.com/1647045/77826077-a3f0a180-7150-11ea-8a91-865a353e7589.png)

**Comment by csheppard** [comment]
+1 yes very useful during development

Was changed in https://github.com/Parallels/rq-dashboard/commit/a9fb11602d9f2efa0a0b4fbcb5d7f4e75eade0bf, why?

**Comment by toshitanian** [comment]
This pull request is this: https://github.com/Parallels/rq-dashboard/pull/243

@coolhacker170597 Did you have any reason to delete the buttons?

**Comment by eoranged** [comment]
It was a limitation of rq library. Will check If that was fixed in 1.3+

**Comment by coolhacker** [comment]
> This pull request is this: #243
> 
> @coolhacker170597 Did you have any reason to delete the buttons?

In 0.5.3 a separate general failed queue was formed to quickly support new functionality at that time. But this crutch significantly affect the performance, so the queue structure was converted into a form that is used in the rq library v1+.

**Comment by goldstar611** [comment]
I just ran this curl command and it worked great:
```
user@workstation:~$ curl -X POST https://myhost/dashboard/queue/failed/empty
{"status":"OK"}
```

**Comment by gnomeby** [comment]
Additional fix was made here: https://github.com/Parallels/rq-dashboard/commit/aa87982e9e288c4abcf4e38176631b5ea1f320d0
