### ISSUE TITLE
instance selector shows full redis url with password

### ISSUE THREAD

**Issue by jtrip** [Parallels/rq-dashboard#359]
Seems like this should be avoided. 

![Screen Shot 2020-09-01 at 5 59 43 PM](https://user-images.githubusercontent.com/125447/91910486-1b38dd00-ec7d-11ea-9c86-f5d728c65629.png)

It might also be more helpful if it had a shorter representation. like just `host:port`

**Comment by jtrip** [comment]
a possible simple update / workaround:

change line 98 in `templates/rq_dashboard/dashboard.js`
```
text: instance.split('@')[1]
```

Although I think perhaps the password should not be passed in the api results at all. I could take a look at that later maybe.

**Comment by eoranged** [comment]
Thanks for report, @jtrip!
What version if rq-dashboard do you use?

**Comment by jtrip** [comment]
You're welcome :) thanks for the consideration.

 This is on 
`VERSION = '0.6.1'`
