### ISSUE TITLE
Incompatible with click==8.0.1

### ISSUE THREAD

**Issue by DuneRaccoon** [Parallels/rq-dashboard#387]
I'm not sure if this issue has been raised, but line 101 in cli.py isn't compatible with the current version of click:

`@click.option(
    '--extra-path', default='.', multiple=True,
    help='Append specified directories to sys.path')`

default must be a list if multiple is True is the error raised.

**Comment by gprasanth** [comment]
#383 #385 trying to fix this very thing, awaiting code review and merge.

**Comment by gprasanth** [comment]
For anyone waiting on the pull request to get merged, you can do `pip install click==7.1.2` after installing `rq-dashboard` to avoid broken deployments in the meanwhile.

**Comment by cjlapao** [comment]
this is now fixed
