### ISSUE TITLE
Update PyPI to Latest Version

### ISSUE THREAD

**Issue by aneuway2** [Parallels/rq-dashboard#393]
Hello! I see that the current latest version is 0.6.3 however on PyPi it is 0.6.1.

Can you please update PyPi with the latest code (or is there a reason why this should not be updated)? Thank you!

**Comment by nhairs** [comment]
Hi!

Bumping this as the latest version is now 0.6.5 :pray:

**Comment by cjlapao** [comment]
@nhairs @aneuway2 We are trying, but at the moment, we cannot find the package owner in PyPi. We tried Vincent, but he no longer maintains it; we are trying the JazzBand as they seem to be the ones Vincent passed on the ownership.

Unfortunately we cannot push there if we do not have access

**Comment by nhairs** [comment]
Thanks for the update @cjlapao

You may be able to file a [PEP541](https://peps.python.org/pep-0541/) request in the [PyPI Support Repository](https://github.com/pypi/support/issues/new/choose) to recover access to one of the new maintainers.

If you believe I can be of assistance please don't hesitate to reach out.

**Comment by cjlapao** [comment]
@nhairs never did one but just raised it. I will keep you guys updated on how this goes along. Once I have access I will then push the current version and update the CI/CD pipeline to do this on each new version

**Comment by nhairs** [comment]
Checking https://pypi.org/project/rq-dashboard/#history it looks like this has been resolved :rocket:

**Comment by cjlapao** [comment]
Yes, forgot to close this issue, it is now automated. so every time we release PyPi will get the same release
