### ISSUE TITLE
Run rq-dashboard from heroku

### ISSUE THREAD

**Issue by gracaninja** [Parallels/rq-dashboard#57]
Hello,

Any way to monitor the rq-dashboard running on heroku in an easy way?

Do you think that something like this would make sense:

https://github.com/jorilallo/celery-flower-heroku

**Comment by klinkin** [comment]
RQ-Dashboard works on Heroku very well. What's problem?

**Comment by nvie** [comment]
Closing old issues.

**Comment by darkpixel** [comment]
Should be pretty easy.  In a new directory, create the following files:

Procfile:

```
web: PYTHONUNBUFFERED=true rq-dashboard --redis_url $REDIS_URL --port $PORT --bind 0.0.0.0
```

requirements.txt:

```
git+https://github.com/nvie/rq-dashboard.git@aaf0e92de9430c4494bb26eab7da18090a7825f5#egg=rq-dashboard
```

Then `git init && git add . && git commit -m 'Initial commit'`

Set up your remotes and git push just like a normal heroku app.
