### ISSUE TITLE
When I run the rq-dashboard I keep getting 500 error

### ISSUE THREAD

**Issue by ghost** [Parallels/rq-dashboard#58]
I can't seem to get this working, I ran the example and even did rq-dashboard on the terminal and I keep getting a 500 error.

Any ideas why?

**Comment by ayoubfaouzi** [comment]
I'm getting the same issue :(

**Comment by mihazelnik** [comment]
run this in terminal and it should work
`brew install redis`
`nohup redis-server &`

**Comment by papisz** [comment]
In my case running with -H, -P and --redis-password helped. But I can't see the data.

**Comment by nvie** [comment]
This should be fixed with the release of [rq-dashboard 0.3.4](https://pypi.python.org/pypi/rq-dashboard). Sorry it took so long!

**Comment by airlsyn** [comment]
when run rq-dashboard, I got the 500 error: "GET / HTTP/1.1" 500

RQ Dashboard version 0.3.5
