### ISSUE TITLE
New version release

### ISSUE THREAD

**Issue by ryanscott** [Parallels/rq-dashboard#66]
Would love to get a new official release, specifically for the worker display fix https://github.com/nvie/rq-dashboard/pull/63  Happy to patch it locally for now, but for production lets get a 3.4 ver out there when possible.  

Thanks!

**Comment by nvie** [comment]
Can you submit a pull request that adds said necessary Python 3.4 support? I'm happy to roll a new release.

**Comment by nvie** [comment]
I declared Python 3 support in [rq-dashboard 0.3.4](https://pypi.python.org/pypi/rq-dashboard).
