### ISSUE TITLE
Upgrade rq

### ISSUE THREAD

**Issue by jjjjw** [Parallels/rq-dashboard#72]
The dashboard is currently pinned to rq >=0.3.8, I think pinning to at least rq >=0.4.0 would be wise, due to bugfixes that rq-dashboard does not benefit from.

**Comment by nvie** [comment]
I'm happy to accept a PR for this.

**Comment by nvie** [comment]
Actually, come to think of it, the reason for the pinning is that without it, rq-dashboard _breaks_. We don't need to pin it to the latest version: this would add to dependency hell. People can simply upgrade RQ at their discretion and work with whatever version they want. Unless a version actually breaks rq-dashboard, we should not pin at all.
