### ISSUE TITLE
How do I block the dashboard via an auth system

### ISSUE THREAD

**Issue by tyler274** [Parallels/rq-dashboard#75]
i.e. in flask-admin  I can hide views to users who don't have a certain role, is there a built in way to block access in rq-dashboard?

**Comment by cosminstefanxp** [comment]
In case it helps anyone, I've managed to get things working with the following snippet:

```
# Prepare the authentication for the RQ dashboard
def _basic_http_auth():
    auth = request.authorization
    return auth and auth.password == PASSWORD and auth.username == USERNAME

# And we register it
rq_dashboard.RQDashboard(application, auth_handler=_basic_http_auth)

# NOTE: RQ Dashboard is registered as a blueprint and thus we can setup a Flask error handler for our case.
# When the configured RQ Dashboard auth_handler returns False, a 401 HTTPException is thrown out, so we can intercept
# it. Thus, we setup an error handler for the rq_dashboard blueprint.
def _auth_exception_handler(error):
    return '', 401, {'WWW-Authenticate': 'Basic realm="Login Required"'}

application.error_handler_spec.setdefault('rq_dashboard', {})[401] = _auth_exception_handler
```

**Comment by jaywink** [comment]
The above snippet was great but now rq-dashboard uses blueprint registering:

    app.config.from_object(rq_dashboard.default_settings)
    app.register_blueprint(rq_dashboard.blueprint, url_prefix="/rq")

Any tips on how to do basic auth in the current version?

**Comment by jaywink** [comment]
If someone else finds this necessary, ended up doing this:

    # auth.py
    from flask import Response, request
    from myapp import app
    

    def check_auth(username, password):
        """This function is called to check if a username password combination is valid."""
        return username == app.config.get("RQ_DASHBOARD_USERNAME") and \
               password == app.config.get("RQ_DASHBOARD_PASSWORD")
    
    
    def authenticate():
        """Sends a 401 response that enables basic auth."""
        return Response(
            'Could not verify your access level for that URL.\n'
            'You have to login with proper credentials', 401,
            {'WWW-Authenticate': 'Basic realm="Login Required"'}
        )
    
    
    def basic_auth():
        """Ensure basic authorization."""
        auth = request.authorization
        if not auth or not check_auth(auth.username, auth.password):
            return authenticate()

Then when registering, add the `before_request` to the blueprint:

    rq_dashboard.blueprint.before_request(basic_auth)
    app.register_blueprint(rq_dashboard.blueprint, url_prefix="/rq")

**Comment by paulmelnikow** [comment]
For the benefit of others who might be seeing this, the build-in server already has this, so if you're running `rq_dashboard` you can pass `--username user --password password` or alternatively set environment variables `RQ_DASHBOARD_USERNAME` and `RQ_DASHBOARD_PASSWORD`.

Using gunicorn requires its own wrapper. I've created one here intended for Heroku: https://github.com/metabolize/rq-dashboard-on-heroku

**Comment by KeyboardInterrupt** [comment]
I am Using `flask-login` and the most straight forward way, I could find was this:

``` python
from flask_login import login_required
import rq_dashboard


@login_required
def rq_login_required():
    """login function used to allow "@login_required" on the before_request function of the rq_dashboard Blueprint"""
    return None

def register_blueprints(app):
    """Register Flask blueprints."""
    rq_dashboard.blueprint.before_request(rq_login_required)
    app.register_blueprint(rq_dashboard.blueprint, url_prefix="/rq")
    return None
```
