### ISSUE TITLE
Flask integration

### ISSUE THREAD

**Issue by jredd** [Parallels/rq-dashboard#88]
the given example, when doing

app.config.from_object(rq_dashboard.default_settings)
app.register_blueprint(rq_dashboard.blueprint)

I receive attribute errors

Traceback (most recent call last):
  File "/my/dev/envi/path/controller_service.py", line 49, in <module>
    app.config.from_object(rq_dashboard.default_settings)
AttributeError: 'module' object has no attribute 'default_settings'

**Comment by adambyrtek** [comment]
Pull request #89 should solve you problem. Let me know if it doesn't.

**Comment by eoranged** [comment]
@jredd could you tell If the issue is fixed for you?

**Comment by eoranged** [comment]
Looks like It is fixed, so closing. Feel free to reopen If you still facing this issue with newer versions of rq-dashboard.
