### ISSUE TITLE
Version on pip is not current

### ISSUE THREAD

**Issue by gregroberts** [Parallels/rq-dashboard#92]
I'm using python 2.7, and when I tried integrating this with an existing flask app, I got the error:

```
    application.config.from_object(rq_dashboard.default_settings)
AttributeError: 'module' object has no attribute 'default_settings'
```

**Comment by gregroberts** [comment]
#88 is the same issue essentially.

**Comment by JokerQyou** [comment]
+1. You should upload `0.3.5dev0` to pip as well

**Comment by TiernanKennedy** [comment]
+1. Any chance of a fix?

**Comment by nvie** [comment]
I just pushed out 0.3.5 to PyPI. Merry christmas :christmas_tree:

**Comment by TiernanKennedy** [comment]
Cheers @nvie! Everything is now working perfectly. :santa:
